export class CompService{
  constructor(){
    this.synth={
      attack:1,
      release:1,
      threshold:40,
      knee:20,
      ratio:10,
      active:true
    }
    this.sidechain={
      attack:0.1,
      release:0.1,
      threshold:55,
      knee:20,
      ratio:10,
      active:true
    }
    this.drums={
      attack:3,
      release:1,
      threshold:90,
      knee:40,
      ratio:2,
      active:true
    }
  }
}
